# Theme 7 – Stone & Lime
[theme]
primaryColor = "#B5FF7D"
backgroundColor = "#0E0F0E"
secondaryBackgroundColor = "#1D1F1D"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true        # required by most PaaS
port = 8501            # default; Streamlit Cloud ignores this

[client]
toolbarMode = "minimal"   # hides “Deploy”, “Share”, etc. for end users