# Theme 5 – Ocean Teal
[theme]
primaryColor = "#1ABC9C"
backgroundColor = "#0B1114"
secondaryBackgroundColor = "#182024"
textColor = "#EAF2F2"
font = "sans serif"

[server]
headless = true        # required by most PaaS
port = 8501            # default; Streamlit Cloud ignores this

[client]
toolbarMode = "minimal"   # hides “Deploy”, “Share”, etc. for end users