# Theme 4 – Brazil Sunset
[theme]
primaryColor = "#FF8C42"
backgroundColor = "#111312"
secondaryBackgroundColor = "#1F2220"
textColor = "#FDFDFD"
font = "sans serif"

[server]
headless = true        # required by most PaaS
port = 8501            # default; Streamlit Cloud ignores this

[client]
toolbarMode = "minimal"   # hides “Deploy”, “Share”, etc. for end users